# Generated by Django 5.0.1 on 2024-02-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='schoolsclgpg',
            new_name='schoolclgpg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='schoolsclgug',
            new_name='schoolclgssc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='schoolsclssc',
            new_name='schoolclgug',
        ),
    ]
